/* Mettle v0.3; generated by build.mjs. No dependencies. */
const FMM=(()=>{
/** Motion adapter contracts checked against Figma's September 2026 live API.
 * Resolved keyframes are data, not programs. Never execute custom style code.
 */
const MOTION_SUPPORT = Object.freeze({
  checkedAt: '2026-09-30',
  customStyles: 'resolved-supported-tracks',
  easingVariables: 'resolved-for-consumer-at-export',
  backEasing: 'source-cubic-required',
  textAnimation: 'whole-node-only; per-character/word not supported',
  audioTimeline: 'not-supported; no published capture contract verified',
  lottie: 'alternative-export; not a Mettle input or dependency'
});
const number = value => typeof value === 'number' && Number.isFinite(value);
const copy = value => JSON.parse(JSON.stringify(value));
function compileEasing(e = {type:'LINEAR'}) {
  if (e?.type === 'VARIABLE_ALIAS') throw new Error('Unresolved easing variable; capture must resolve it for this node.');
  if (e?.type === 'HOLD') return {kind:'hold', control:[]};
  const named = {LINEAR:[], EASE_IN:[.42,0,1,1], EASE_OUT:[0,0,.58,1], EASE_IN_AND_OUT:[.42,0,.58,1]};
  const back = ['EASE_IN_BACK','EASE_OUT_BACK','EASE_IN_AND_OUT_BACK'];
  if (!(e?.type in named) && !back.includes(e?.type) && e?.type !== 'CUSTOM_CUBIC_BEZIER') {
    throw new Error(`Easing ${e?.type} needs a native implementation; springs are not approximated.`);
  }
  // Explicit source values take precedence over generic CSS named curves. Do not
  // mistake a cached cubic on a spring object for the spring itself.
  if (e.easingFunctionCubicBezier !== undefined) {
    const c=e.easingFunctionCubicBezier, control=[c?.x1,c?.y1,c?.x2,c?.y2];
    if (!control.every(number) || control[0]<0 || control[0]>1 || control[2]<0 || control[2]>1) {
      throw new Error('Invalid source cubic; expected finite controls and x in 0...1.');
    }
    if (e.type==='LINEAR' && control[0]===control[1] && control[2]===control[3]) return {kind:'linear',control:[]};
    return {kind:'cubic',control};
  }
  if (back.includes(e.type) || e.type==='CUSTOM_CUBIC_BEZIER') throw new Error(`${e.type} requires its exact source cubic.`);
  return {kind:e.type==='LINEAR'?'linear':'cubic',control:[...named[e.type]]};
}

/** Preset keyframe times are local to the style in the observed API. Manual
 * keyframes are already timeline-relative. `props.delay` duplicates placement;
 * adding it a second time is incorrect. Duration is already reflected in keys.
 */
function trackPlacement(track, styles = []) {
  const preset=track.animationPreset;
  if (!preset) return 0;
  if (typeof preset.id!=='string' || !preset.id) throw new Error('Style track is missing its source instance ID.');
  const owner=styles.find(style=>style.id===preset.id);
  const offset=preset.timelineOffset ?? owner?.timelineOffset;
  if (!number(offset) || offset<0 || offset>86400) throw new Error('Style timelineOffset is missing, unresolved, or out of range.');
  const duration=preset.duration ?? owner?.duration;
  if (duration!==undefined && (!number(duration) || duration<0 || duration>86400)) throw new Error('Invalid style duration.');
  // Evidence: a one-second style's keys already span 0...1, not 0...100%.
  if (duration!==undefined && track.keyframes?.some(k=>k.timelinePosition>duration+1e-5)) {
    throw new Error('Style keys extend beyond its duration; timing convention is not recognized.');
  }
  return offset;
}

function styleCoverage(source, report) {
  const styles=source.animationStyles ?? [];
  if (!styles.length) return;
  if (!Array.isArray(styles) || styles.length>64) throw new Error('Expected at most 64 applied animation styles.');
  const resolved=source.animations ?? {};
  const linked=new Set();
  function visit(value,depth=0) {
    if (!value || typeof value!=='object' || depth>40) return;
    if (Array.isArray(value.tracks)) for (const track of value.tracks) {
      if (track.animationPreset?.id) linked.add(track.animationPreset.id);
    }
    for (const [key,child] of Object.entries(value)) if (key!=='animationPreset' && key!=='keyframes') visit(child,depth+1);
  }
  visit(resolved);
  for (const style of styles) {
    if (!style.id || !linked.has(style.id)) report('error','UNRESOLVED_ANIMATION_STYLE',source,
      `Style ${style.name ?? style.id ?? '(unnamed)'} has no attributable resolved tracks. Wait for Figma to resolve it, then export again; it was not replaced with manual or static content.`);
  }
}

/** A host can expose only part of its resolved animation object. Choosing that
 * object wholesale used to drop manual fields (including indexed paint tracks)
 * without a diagnostic. Do not merge them speculatively: resolved tracks can
 * compose with styles, so their order is significant. Keep both source payloads
 * and require Figma to expose a complete binding before claiming an export.
 */
function manualCoverage(source, report) {
  const resolved=source.animations??{};
  if(!Object.keys(resolved).length) return;
  let visited=0;
  function visit(manual,target,path,depth=0) {
    if(++visited>200000 || depth>48) throw new Error('Manual motion coverage budget exceeded.');
    if(!manual || typeof manual!=='object') return;
    if(Array.isArray(manual.keyframes)) {
      if(!manual.keyframes.length) return;
      const tracks=target?.tracks;
      const missing=!Array.isArray(tracks) || !tracks.some(t=>Array.isArray(t.keyframes)&&t.keyframes.length);
      const missingID=!missing && typeof manual.id==='string' && tracks.every(t=>typeof t.id==='string') && !tracks.some(t=>t.id===manual.id);
      if(missing || missingID) report('error','UNRESOLVED_MANUAL_TRACK',source,
        `Manual track ${path} is absent from the resolved animations. Wait for Figma to resolve it, then export again; it was not silently dropped or reordered.`);
      return;
    }
    for(const [key,child] of Object.entries(manual)) visit(child,target?.[key],path?`${path}.${key}`:key,depth+1);
  }
  visit(source.manualKeyframeTracks,resolved,'');
}

/** Resolve tokens in the consumer's effective variable mode, not the collection
 * default. Raw aliases are retained separately by capture for audit/re-export.
 */
async function resolveMotionVariables(figma, consumer, raw) {
  const resolutions=[],cache=new Map(); let visited=0;
  async function resolve(value,path,depth=0,chain=[]) {
    if (++visited>200000 || depth>48) throw new Error('Motion variable resolution budget exceeded.');
    if (value===null || typeof value!=='object') return value;
    if (value.type==='VARIABLE_ALIAS') {
      if (typeof value.id!=='string' || !value.id || chain.includes(value.id) || chain.length>=16) throw new Error(`Cyclic or invalid motion alias at ${path}.`);
      if (!figma.variables?.getVariableByIdAsync) throw new Error('This host cannot resolve motion variables.');
      let token=cache.get(value.id);
      if (!token) {
        token=(async()=>{
        const variable=await figma.variables.getVariableByIdAsync(value.id);
        if (!variable || typeof variable.resolveForConsumer!=='function') throw new Error(`Motion variable ${value.id} is unavailable.`);
        const result=await variable.resolveForConsumer(consumer);
        if (!result || result.value===undefined) throw new Error(`Motion variable ${value.id} did not resolve.`);
        return copy(result);
        })();cache.set(value.id,token);
      }
      token=await token;
      const resolved=await resolve(token.value,path,depth+1,[...chain,value.id]);
      resolutions.push({path,id:value.id,resolvedType:token.resolvedType,value:copy(resolved)});
      return resolved;
    }
    if (Array.isArray(value)) return Promise.all(value.map((item,index)=>resolve(item,`${path}[${index}]`,depth+1,chain)));
    const out={};
    for (const [key,child] of Object.entries(value)) {
      // Avoid prototype mutation even with externally supplied JSON snapshots.
      Object.defineProperty(out,key,{value:await resolve(child,`${path}.${key}`,depth+1,chain),enumerable:true,writable:true,configurable:true});
    }
    return out;
  }
  const resolved=await resolve(raw,'motion');
  resolutions.sort((a,b)=>a.path<b.path?-1:a.path>b.path?1:a.id<b.id?-1:1);
  return {resolved,resolutions};
}

return {compileEasing,trackPlacement,styleCoverage,manualCoverage,MOTION_SUPPORT,resolveMotionVariables};
})();
const FM=(()=>{
const {compileEasing,trackPlacement,styleCoverage,manualCoverage,MOTION_SUPPORT}=FMM;
/** Deterministic Figma snapshot -> native scene compiler. Zero runtime dependencies.
 * Kept separate from the Figma host so source semantics can be unit-tested in Node.
 * Matrices are column-vector affine; times are seconds; source geometry is never traced.
 */
const IDENTITY = Object.freeze({ a:1,b:0,c:0,d:1,tx:0,ty:0 });
const rgba = (r=1,g=1,b=1,a=1) => ({r,g,b,a});
const point = (x=0,y=0) => ({x,y});
const json = x => JSON.parse(JSON.stringify(x));
const equal = (a,b) => JSON.stringify(a) === JSON.stringify(b);
const finite = x => typeof x === 'number' && Number.isFinite(x);
const clamp = x => Math.min(1,Math.max(0,x));
function affine(t) {
  if (!Array.isArray(t) || t.length !== 2 || t.some(row => !Array.isArray(row) || row.length !== 3 || !row.every(finite))) {
    throw new Error('Expected a finite Figma 2×3 transform');
  }
  return {a:t[0][0],b:t[1][0],c:t[0][1],d:t[1][1],tx:t[0][2],ty:t[1][2]};
}
function multiply(l,r) {
  return {a:l.a*r.a+l.c*r.b,b:l.b*r.a+l.d*r.b,c:l.a*r.c+l.c*r.d,d:l.b*r.c+l.d*r.d,
    tx:l.a*r.tx+l.c*r.ty+l.tx,ty:l.b*r.tx+l.d*r.ty+l.ty};
}
function inverse(t) {
  const det=t.a*t.d-t.b*t.c;
  if (!finite(det) || Math.abs(det)<1e-12) throw new Error('Singular source transform');
  return {a:t.d/det,b:-t.b/det,c:-t.c/det,d:t.a/det,tx:(t.c*t.ty-t.d*t.tx)/det,ty:(t.b*t.tx-t.a*t.ty)/det};
}
function value(v) {
  if (v?.type==='FLOAT' && finite(v.value)) return [v.value];
  if (v?.type==='COLOR' && ['r','g','b','a'].every(k=>finite(v.value?.[k]))) return ['r','g','b','a'].map(k=>v.value[k]);
  if (v?.type==='VECTOR' && finite(v.value?.x) && finite(v.value?.y)) return [v.value.x,v.value.y];
  throw new Error(`Unsupported or unresolved keyframe value ${v?.type}`);
}
const easing = compileEasing;

function paint(p,report,node) {
  if (p.visible===false) return null;
  if (p.blendMode && p.blendMode!=='NORMAL') { report('error','PAINT_BLEND',node,`Paint blend ${p.blendMode} is unsupported.`); return null; }
  if (p.type==='SOLID') return {kind:'solid',color:rgba(p.color.r,p.color.g,p.color.b),opacity:p.opacity??1,transform:IDENTITY,stops:[]};
  if (['GRADIENT_LINEAR','GRADIENT_RADIAL'].includes(p.type)) {
    if (!Array.isArray(p.gradientStops) || p.gradientStops.length<2 || p.gradientStops.length>64) {
      report('error','GRADIENT_STOPS',node,'Expected 2...64 gradient stops.');return null;
    }
    return {kind:p.type==='GRADIENT_LINEAR'?'linear':'radial',color:rgba(),opacity:p.opacity??1,
      transform:affine(p.gradientTransform),stops:json(p.gradientStops).map(s=>({position:s.position,color:s.color}))};
  }
  report('error','UNSUPPORTED_PAINT',node,`${p.type} paint needs a native implementation. No raster substitute was made.`);return null;
}
function paths(source,report,node) {
  const result=[];
  for (const p of source??[]) {
    if (!['NONZERO','EVENODD'].includes(p.windingRule)) {
      report('error','PATH_WINDING',node,`Unsupported winding ${p.windingRule}.`);continue;
    }
    if (typeof p.data!=='string' || p.data.length>2_000_000) {
      report('error','PATH_DATA',node,'Missing or excessive path data.');continue;
    }
    result.push({data:p.data,windingRule:p.windingRule});
  }
  return result;
}
function drawings(geometry,paints,size,transform,role,report,node) {
  if (paints==='MIXED') { report('error','MIXED_PAINTS',node,'Mixed/rich-text paints require region-level export.');return []; }
  const out=[];const ps=paths(geometry,report,node);
  if (!ps.length && (paints??[]).some(p=>p.visible!==false)) report('error','MISSING_GEOMETRY',node,`No ${role} geometry was exposed.`);
  // Live Figma conformance confirms the API paint array is bottom-to-top.
  for(let index=0;index<(paints??[]).length;index++) {
    const p=paint(paints[index],report,node);
    if(p && ps.length) out.push({paths:ps,paint:p,transform,size,paintIndex:index,role});
  }
  return out;
}
function motionBindings(source,report,options) {
  styleCoverage(source,report);
  manualCoverage(source,report);
  const animations=source.animations;
  const manual=source.manualKeyframeTracks;
  const hasResolved=animations && Object.keys(animations).length>0;
  const data=hasResolved?animations:(manual??{});
  const result=[];
  if (!hasResolved && Object.keys(data).length) report('warning','MANUAL_TRACK_FALLBACK',source,'Resolved animations unavailable; only exposed manual tracks are exported.');
  const map={TRANSLATION_X:['translationX'],TRANSLATION_Y:['translationY'],TRANSLATION_XY:['translationX','translationY'],
    OPACITY:['opacity'],ROTATION:['rotation'],SCALE_X:['scaleX'],SCALE_Y:['scaleY'],SCALE_XY:['scaleX','scaleY']};
  function add(field,binding,component) {
    try {
      const baseAll=value(binding.baseValue);
      const base=component===undefined?baseAll:[baseAll[component]];
      if (!base.every(finite)) throw new Error('Binding base dimensions do not match field');
      const sourceTracks=binding.tracks??[{keyframeOperation:'SET',keyframes:binding.keyframes}];
      if(!Array.isArray(sourceTracks) || !sourceTracks.length) throw new Error('Empty or invalid resolved track list');
      const tracks=sourceTracks.map(track=>{
        const timelineOffset=trackPlacement(track,source.animationStyles);
        const op=String(track.keyframeOperation??'SET').toLowerCase();
        if(!['set','offset','scale'].includes(op)) throw new Error(`Unknown track operation ${op}`);
        let previous=-Infinity;
        const keyframes=(track.keyframes??[]).map(k=>{
          if(!finite(k.timelinePosition)||k.timelinePosition<0||k.timelinePosition<=previous) throw new Error('Unsorted/duplicate keyframe times');
          previous=k.timelinePosition;
          const all=value(k.value);const v=component===undefined?all:[all[component]];
          if(v.length!==base.length || !v.every(finite)) throw new Error('Keyframe dimensions differ from base');
          return {time:k.timelinePosition,value:v,easing:easing(k.easing)};
        });
        if(!keyframes.length) throw new Error('Empty motion track');
        return {operation:op,keyframes,...(timelineOffset!==0?{timelineOffset}:{})};
      });
      if (tracks.length>64) throw new Error('At most 64 tracks per field are supported');
      const needed=field.includes(':')?4:1;
      if(base.length!==needed) throw new Error('Field/value dimension mismatch');
      if((field==='scaleX'||field==='scaleY')&&Math.abs(base[0])<1e-12) throw new Error('Cannot normalize scale from zero');
      // Figma Motion translation values are OFFSETS, unlike A→B absolute positions.
      // Live frame 2:9: static x=24, source keyframe=24, Figma renders x=48.
      // A resolved binding.baseValue may already include the static position.
      // Use a zero anchor for SET-led offset tracks; preserve raw sourceMotion.
      if(field==='translationX'||field==='translationY') {
        if(tracks[0]?.operation!=='set' && !tracks.every(t=>t.operation==='offset')) throw new Error('Non-SET translation supports additive OFFSET tracks only; SCALE-leading semantics remain unverified.');
        result.push({field,base:[0],tracks});
      } else result.push({field,base,tracks});
    } catch(error) { report('error','MOTION_BINDING',source,`${field}: ${error.message}`); }
  }
  for(const [name,binding] of Object.entries(data)) {
    if(!binding) continue;
    if(map[name]) {
      if(['ROTATION','SCALE_X','SCALE_Y','SCALE_XY'].includes(name)) {
        report('warning','EXPLICIT_TRANSFORM_ORIGIN',source,`Motion API does not supply a pivot here. Export uses the explicitly selected ${options.origin??'center'} origin; verify against Figma.`);
      }
      map[name].forEach((field,i)=>{
        if(result.some(b=>b.field===field)) report('error','DUPLICATE_MOTION_FIELD',source,`${field} is bound twice (for example XY and X); source composition is ambiguous.`);
        else add(field,binding,map[name].length>1?i:undefined);
      });
    } else if(name==='fills'||name==='strokes') {
      for(const [index,paintBinding] of Object.entries(binding)) {
        if(paintBinding?.properties) {report('error','SHADER_PROPERTY_MOTION',source,`${name}[${index}] shader parameter tracks are not implemented.`);continue;}
        const sourcePaint=source[name]?.[Number(index)];
        if(sourcePaint?.type!=='SOLID') {report('error','NON_SOLID_COLOR_MOTION',source,`${name}[${index}] color animation requires a solid paint.`);continue;}
        add(`${name}:${index}`,paintBinding);
      }
    } else {report('error','UNSUPPORTED_MOTION_FIELD',source,`${name} motion is not implemented. Its source data is retained.`);}
  }
  return result;
}

function compileScene(snapshot,options={}) {
  const diagnostics=[];
  const sourceMotion={};
  const report=(severity,code,node,message)=>diagnostics.push({severity,code,nodeID:node.id??'',message});
  let duration=0,count=0;
  const timelineIDs=new Set();
  const viewport=options.viewport;
  if(viewport!==undefined && (!viewport || Array.isArray(viewport) || !['x','y','width','height'].every(key=>finite(viewport[key])) ||
    viewport.width<=0||viewport.height<=0||viewport.width>16384||viewport.height>16384)) {
    throw new Error('Viewport requires finite local x/y and positive width/height at most 16384');
  }
  function visit(source,root=false,depth=0) {
    if(++count>5000||depth>64) throw new Error('Export node/depth budget exceeded');
    if(!finite(source.width)||!finite(source.height)||source.width<0||source.height<0) throw new Error(`Invalid dimensions for ${source.id}`);
    for(const issue of source.captureDiagnostics??[]) report(issue.severity??'error',issue.code,source,issue.message);
    if(source.effects?.some(e=>e.visible!==false)) report('error','EFFECTS',source,'Blur, shadow, shader, and other effects need native render passes; no effect was silently approximated.');
    if(source.isMask) report('error','SIBLING_MASK',source,'Sibling alpha/vector masks are not implemented. Frame clipsContent is supported.');
    if(source.blendMode&&!['NORMAL','PASS_THROUGH'].includes(source.blendMode)) report('error','NODE_BLEND',source,`Node blend ${source.blendMode} is unsupported.`);
    if(source.regionalPaints) report('error','REGIONAL_PAINTS',source,'Vector regions have independent paints; region-level extraction is not implemented.');
    if(source.layoutMode&&source.layoutMode!=='NONE') report('info','LAYOUT_SNAPSHOT',source,'Resolved layout is exported at this size. No responsive layout engine is included.');
    const ownTransform=affine(source.relativeTransform??[[1,0,0],[0,1,0]]);
    const output={id:source.id,name:source.name??source.id,transform:root?(viewport?{...IDENTITY,tx:-viewport.x,ty:-viewport.y}:IDENTITY):ownTransform,
      size:point(source.width,source.height),opacity:source.visible===false?0:(source.opacity??1),
      origin:options.origin==='topLeft'?point():point(source.width/2,source.height/2),draws:[],clip:[],bindings:[],children:[]};
    const geometrySource=source.outlinedText??source;
    const fillTransform=source.outlinedText?(geometrySource.localTransform??multiply(inverse(ownTransform),affine(geometrySource.relativeTransform))):IDENTITY;
    output.draws.push(...drawings(geometrySource.fillGeometry,geometrySource.fills,
      point(geometrySource.width,geometrySource.height),fillTransform,'fills',report,source));
    if(source.outlinedText) report('info','TEXT_OUTLINED',source,'Text is exported as native vector outlines, not font files or raster pixels. Text is no longer editable in the player.');
    if(source.strokeOutline) {
      const s=source.strokeOutline;
      output.draws.push(...drawings(s.fillGeometry,s.fills,point(s.width,s.height),
        s.localTransform??multiply(inverse(ownTransform),affine(s.relativeTransform)),'strokes',report,source));
    } else if(source.strokes?.some?.(p=>p.visible!==false)) {
      if(source.strokeAlign==='CENTER') output.draws.push(...drawings(source.strokeGeometry,source.strokes,output.size,IDENTITY,'strokes',report,source));
      else report('error','STROKE_OUTLINE',source,'Inside/outside strokes require successful source outline extraction.');
    }
    if(source.clipsContent) {
      output.clip=paths(source.fillGeometry,report,source);
      if(!output.clip.length) report('error','CLIP_GEOMETRY',source,'Figma did not expose the clipping path.');
    }
    if(options.includeMotion!==false && source.visible!==false) {
      output.bindings=motionBindings(source,report,options);
      for(const b of output.bindings) for(const t of b.tracks) for(const k of t.keyframes) duration=Math.max(duration,k.time+(t.timelineOffset??0));
      for(const binding of Object.values(source.animations??{})) if(finite(binding?.timelineDuration)) duration=Math.max(duration,binding.timelineDuration);
      for(const timeline of source.timelines??[]) { if(finite(timeline.duration)) duration=Math.max(duration,timeline.duration);if(timeline.id) timelineIDs.add(timeline.id); }
    }
    if(Object.keys(source.animations??{}).length||Object.keys(source.manualKeyframeTracks??{}).length||source.animationStyles?.length||source.timelines?.length||source.reactions?.length) {
      sourceMotion[source.id]={...(source.rawMotion??{animations:source.animations??null,manualKeyframeTracks:source.manualKeyframeTracks??null,animationStyles:source.animationStyles??[]}),
        timelines:source.timelines??[],variableResolutions:source.motionVariableResolutions??[],...(source.reactions?.length?{reactions:json(source.reactions)}:{})};
    }
    if(options.includePrototypeWarnings!==false && source.reactions?.length) report('warning','PROTOTYPE_EVENTS_NOT_EXPORTED',source,'Interactive event wiring is not part of a single-scene export. Use the two-frame compiler for a constrained A→B clip.');
    if(options.includeMotion!==false) for(const timeline of source.timelines??[]) {
      const unknown=Object.keys(timeline).filter(key=>!['id','duration'].includes(key));
      if(unknown.length) report('error','UNSUPPORTED_TIMELINE_DATA',source,`Timeline contains unhandled fields: ${unknown.join(', ')}. Audio and new timeline payloads must not be silently lost.`);
    }
    let children=(source.children??[]).filter(c=>c.visible!==false);
    if(source.itemReverseZIndex) children=[...children].reverse();
    output.children=children.map(c=>visit(c,false,depth+1));
    return output;
  }
  const root=visit(snapshot,true);
  if(timelineIDs.size>1) report('error','MULTIPLE_TIMELINES',snapshot,'Independent/nested timelines need explicit coordination; this player exports a single timeline.');
  const scene={name:snapshot.name??'Figma scene',width:viewport?.width??snapshot.width,height:viewport?.height??snapshot.height,duration,loop:options.loop??'once',root};
  return {format:'figma-metal',version:2,scenes:[scene],diagnostics,sourceMotion,motionSupport:{...MOTION_SUPPORT},exporter:{name:'Mettle',version:'0.3.0',source:'Figma Plugin API'}};
}

/** Strict, bounded Smart-Animate-style A→B compiler: stable geometry, translation,
 * opacity, solid colors and solid fill appearance. Rejects topology/size/rotation
 * changes instead of crossfading them.
 * Match by unique hierarchical layer NAME, never by guessed pixel proximity.
 */
function compileTransition(a,b,options={}) {
  const first=compileScene(a,{...options,includeMotion:false,includePrototypeWarnings:false}),second=compileScene(b,{...options,includeMotion:false,includePrototypeWarnings:false});
  first.diagnostics.push(...second.diagnostics);
  const report=(code,id,message)=>first.diagnostics.push({severity:'error',code,nodeID:id,message});
  const duration=options.duration??.6;
  const delay=options.delay??0;
  if(!finite(duration)||duration<=0||duration>3600) throw new Error('Transition duration must be greater than 0 and at most 3600 seconds');
  if(!finite(delay)||delay<0||delay>3600) throw new Error('Transition delay must be 0...3600 seconds');
  const ease=easing(options.easing??{type:'EASE_IN_AND_OUT'});
  first.scenes[0].duration=delay+duration;first.scenes[0].name=`${a.name} → ${b.name}`;
  if(a.width!==b.width||a.height!==b.height) report('TRANSITION_SIZE',a.id,'A and B must have the same frame dimensions.');
  const indexSource=root=>{
    const index=new Map();
    function visit(node) {index.set(node.id,node);for(const child of node.children??[]) if(child.visible!==false) visit(child);}
    visit(root);return index;
  };
  const sourcesA=indexSource(a),sourcesB=indexSource(b);
  function sameUnpaintedGeometry(draw,source) {
    const geometry=source.outlinedText??source;
    const transform=source.outlinedText?(geometry.localTransform??multiply(inverse(affine(source.relativeTransform??[[1,0,0],[0,1,0]])),affine(geometry.relativeTransform))):IDENTITY;
    const geometryPaths=(geometry.fillGeometry??[]).map(path=>({data:path.data,windingRule:path.windingRule}));
    return equal(draw.paths,geometryPaths)&&equal(draw.transform,transform)&&equal(draw.size,point(geometry.width,geometry.height));
  }
  function track(node,field,base,target) {
    if(equal(base,target)) return;
    node.bindings.push({field,base,tracks:[{operation:'set',...(delay?{timelineOffset:delay}:{}),keyframes:[{time:0,value:base,easing:ease},{time:duration,value:target,easing:{kind:'linear',control:[]}}]}]});
  }
  function compare(x,y) {
    if(!equal(x.size,y.size)||!equal(x.clip,y.clip)) report('TRANSITION_GEOMETRY',x.id,'Animated size/clip geometry is not implemented.');
    if(['a','b','c','d'].some(k=>Math.abs(x.transform[k]-y.transform[k])>1e-7)) report('TRANSITION_LINEAR_TRANSFORM',x.id,'A→B rotation, skew, or scale changes are not implemented.');
    track(x,'translationX',[x.transform.tx],[y.transform.tx]);track(x,'translationY',[x.transform.ty],[y.transform.ty]);
    track(x,'opacity',[x.opacity],[y.opacity]);
    const drawKey=draw=>`${draw.role}:${draw.paintIndex}`;
    const fromDraws=new Map(x.draws.map(draw=>[drawKey(draw),draw]));
    const toDraws=new Map(y.draws.map(draw=>[drawKey(draw),draw]));
    for(const key of new Set([...fromDraws.keys(),...toDraws.keys()])) {
      let d=fromDraws.get(key),target=toDraws.get(key);
      if(!d||!target) {
        const existing=d??target;
        // Material's real Switch hover state adds a solid state-layer fill to
        // an existing, unchanged circle. A transparent endpoint of that exact
        // source fill is sufficient; no contour or color has to be invented.
        if(existing.role!=='fills'||existing.paint.kind!=='solid') {
          report('TRANSITION_DRAW_COUNT',x.id,'Only solid fills on unchanged source geometry can appear or disappear.');continue;
        }
        if(!sameUnpaintedGeometry(existing,d?sourcesB.get(y.id):sourcesA.get(x.id))) {
          report('TRANSITION_DRAW_GEOMETRY',x.id,'An appearing/disappearing fill also changes source geometry; shape morphs are not implemented.');continue;
        }
        const transparent=json(existing);transparent.paint.opacity=0;
        if(!d) {d=transparent;x.draws.push(d);} else target=transparent;
      }
      if(!equal(d.paths,target.paths)||!equal(d.transform,target.transform)||!equal(d.size,target.size)||d.role!==target.role||d.paintIndex!==target.paintIndex) {
        report('TRANSITION_DRAW_GEOMETRY',x.id,'Path morphs/different source geometry are not implemented.');continue;
      }
      if(d.paint.kind==='solid'&&target.paint.kind==='solid') {
        const effective=p=>[p.color.r,p.color.g,p.color.b,p.color.a*p.opacity];
        track(x,`${d.role}:${d.paintIndex}`,effective(d.paint),effective(target.paint));
      } else if(!equal(d.paint,target.paint)) report('TRANSITION_PAINT',x.id,'Animated gradients are not implemented.');
    }
    // Newly admitted fills keep the source's paint-stack order and stay below
    // strokes, including when some source paint entries were invisible.
    x.draws.sort((l,r)=>(l.role===r.role?l.paintIndex-r.paintIndex:l.role==='fills'?-1:1));
    const names=x.children.map(n=>n.name),other=y.children.map(n=>n.name);
    if(new Set(names).size!==names.length||new Set(other).size!==other.length) {report('AMBIGUOUS_LAYER_NAMES',x.id,'Sibling names must be unique for deterministic matching.');return;}
    if(!equal(names,other)) {report('TRANSITION_HIERARCHY',x.id,'Layer additions/removals/reordering are not implemented.');return;}
    x.children.forEach((child,i)=>compare(child,y.children[i]));
  }
  compare(first.scenes[0].root,second.scenes[0].root);
  first.sourceMotion={from:first.sourceMotion,to:second.sourceMotion};
  first.exporter.mode='two-frame-transition';
  return first;
}

return {compileScene,compileTransition};
})();
const FMC=(()=>{
const {resolveMotionVariables}=FMM;
/** Shared, capability-guarded live Figma capture. No UI, compiler, or network. */
function createCapture(figma) {
let captureCount = 0;
const audit = {created:[], removed:[]};
const temporaryIDs = new Set();
const cloneJSON = value => value == null ? value : JSON.parse(JSON.stringify(value));
const read = (node, key, fallback) => {
  if (!(key in node)) return fallback;
  try { const value=node[key]; return value===undefined?fallback:cloneJSON(value); }
  catch(error) { throw new Error(`Cannot read source property ${key} on ${node.id}: ${error.message??error}`); }
};
function capturePaints(node,key) {
  if(!(key in node)) return [];
  return node[key]===figma.mixed?'MIXED':cloneJSON(node[key]);
}
function geometrySnapshot(node) {
  const fills=capturePaints(node,'fills');
  return {width:node.width,height:node.height,relativeTransform:cloneJSON(node.relativeTransform),
    fillGeometry:read(node,'fillGeometry',[]),fills,
    regionalPaints:read(node,'vectorNetwork',{}).regions?.some(region=>region.fills?.length && JSON.stringify(region.fills)!==JSON.stringify(fills))??false};
}
async function outlineGeometry(node, text) {
  // Reparent a temporary copy out of auto layout before conversion. This avoids
  // baking transient auto-layout shifts into exported text/stroke coordinates.
  const width=node.width,height=node.height;
  const temporary=[];
  const page=figma.currentPage;
  const previousSelection=page&&Array.isArray(page.selection)?Array.from(page.selection):null;
  let changedSelection=false;
  function observeTemporarySelection() {
    if(page&&page===figma.currentPage&&Array.from(page.selection).some(node=>temporaryIDs.has(node.id))) changedSelection=true;
  }
  function remember(node) {
    audit.created.push(node.id);temporaryIDs.add(node.id);temporary.push(node);observeTemporarySelection();
  }
  let stage=null,copy=null,outline=null;
  try {
    stage=figma.createFrame();remember(stage);stage.name='__Mettle temporary outline workspace';
    stage.visible=false;stage.fills=[];stage.clipsContent=false;
    copy=node.clone();remember(copy);stage.appendChild(copy);copy.relativeTransform=[[1,0,0],[0,1,0]];
    if((copy.width!==width||copy.height!==height)&&typeof copy.resizeWithoutConstraints==='function') copy.resizeWithoutConstraints(width,height);
    outline=text?figma.flatten([copy],stage):copy.outlineStroke();
    if(outline) remember(outline);
    if(!outline) throw new Error('Source outline operation returned no geometry');
    const data=geometrySnapshot(outline),m=data.relativeTransform;
    data.localTransform={a:m[0][0],b:m[1][0],c:m[0][1],d:m[1][1],tx:m[0][2],ty:m[1][2]};
    if(data.regionalPaints) throw new Error('Outlined geometry contains independent regional paints');
    return data;
  } finally {
    observeTemporarySelection();
    if(stage&&!stage.removed)stage.remove();
    if(copy&&!copy.removed)copy.remove();
    if(outline&&!outline.removed)outline.remove();
    for(const n of temporary) if(n.removed&&!audit.removed.includes(n.id)) audit.removed.push(n.id);
    // Only this synchronous block mutates document selection. Its snapshot is
    // taken after any earlier async font/component reads, so a user selection
    // made while those reads were pending is not rewound to the export's start.
    if(changedSelection&&previousSelection&&page===figma.currentPage&&
      Array.from(page.selection).every(node=>node.removed||temporaryIDs.has(node.id))) {
      page.selection=previousSelection.filter(node=>!node.removed);
    }
  }
}
async function captureNode(node,options={}) {
  // Prototype endpoints and explicit static exports do not consume Figma's
  // independently gated Motion beta. A getter can exist yet throw on accounts
  // without Motion: never probe it for these modes, and never treat a failing
  // getter as an empty animation in a motion export.
  return visit(node,0,options);
}
async function visit(node,depth,options) {
  if(depth>64||++captureCount>5000) throw new Error('Export exceeds 64 levels or 5000 nodes');
  const captureDiagnostics=[];
  const out={id:node.id,name:node.name,type:node.type,...geometrySnapshot(node),
    visible:node.visible,opacity:read(node,'opacity',1),blendMode:read(node,'blendMode','NORMAL'),
    strokes:capturePaints(node,'strokes'),strokeGeometry:read(node,'strokeGeometry',[]),strokeAlign:read(node,'strokeAlign','CENTER'),
    effects:read(node,'effects',[]),isMask:read(node,'isMask',false),clipsContent:read(node,'clipsContent',false),
    layoutMode:read(node,'layoutMode','NONE'),itemReverseZIndex:read(node,'itemReverseZIndex',false),
    animations:options.includeMotion===false?{}:read(node,'animations',{}),
    manualKeyframeTracks:options.includeMotion===false?{}:read(node,'manualKeyframeTracks',{}),
    animationStyles:options.includeMotion===false?[]:read(node,'animationStyles',[]),
    timelines:options.includeMotion===false?[]:read(node,'timelines',[]),reactions:read(node,'reactions',[]),
    children:[],captureDiagnostics};
  if(depth===0) for(const property of ['absoluteTransform','absoluteRenderBounds','absoluteBoundingBox']) {
    if(property in node) out[property]=read(node,property,null);
  }
  // CHANGE_TO reactions target the main component's variant ID, not an
  // instance's scene ID. Retain that verified identity for matching two
  // selected instances. Never clone the live ComponentNode (it is cyclic),
  // and never use the synchronous getter in dynamic-page plugins.
  if(node.type==='INSTANCE') {
    try {
      if(!('getMainComponentAsync' in node) || typeof node.getMainComponentAsync!=='function') throw new Error('The host does not expose getMainComponentAsync');
      const main=await node.getMainComponentAsync();
      if(!main || typeof main.id!=='string' || !main.id) throw new Error('The main component is unavailable');
      out.sourceComponent={id:main.id,name:read(main,'name',main.id),key:read(main,'key',null)};
    } catch(error) {captureDiagnostics.push({severity:'warning',code:'INSTANCE_COMPONENT_UNAVAILABLE',message:`Source variant identity could not be read: ${error.message??error}. Automatic prototype direction may need an explicit start selection.`});}
  }
  // Keep raw source aliases and custom-style metadata. Compile only resolved
  // consumer-mode data; a missing token is an error, never a default easing.
  out.rawMotion={animations:cloneJSON(out.animations),manualKeyframeTracks:cloneJSON(out.manualKeyframeTracks),animationStyles:cloneJSON(out.animationStyles)};
  try {
    const tokens=await resolveMotionVariables(figma,node,out.rawMotion);
    Object.assign(out,tokens.resolved);out.motionVariableResolutions=tokens.resolutions;
  } catch(error) {captureDiagnostics.push({code:'MOTION_VARIABLE_UNRESOLVED',message:error.message});}
  if(options.includeMotion!==false) {
    if(out.animationStyles.length && !Object.keys(out.animations).length) captureDiagnostics.push({code:'PRESET_MOTION_UNAVAILABLE',message:'Node has animation styles but no resolved animation data was exposed.'});
    if(!('animations' in node)&&!('manualKeyframeTracks' in node)) captureDiagnostics.push({severity:'warning',code:'MOTION_API_UNAVAILABLE',message:'Motion properties are unavailable in this Figma host. Verify that the source is static.'});
  } else out.motionCapture='not-requested';
  // Figma exposes glyph outlines directly on uniform text in supported hosts.
  // Prefer that source geometry; flattening text is not supported by every host.
  if(node.type==='TEXT') {
    try {
      if(out.fills==='MIXED') throw new Error('Mixed text colors are not yet supported');
      if(node.hasMissingFont) throw new Error('Text has a missing font');
      if(out.fillGeometry.length) {
        out.textGeometry='source-glyph-paths';
        captureDiagnostics.push({severity:'info',code:'TEXT_SOURCE_OUTLINES',message:'Uniform text uses Figma-provided glyph paths. No font file or raster image is exported.'});
      } else {
        for(const font of node.getRangeAllFontNames(0,node.characters.length)) await figma.loadFontAsync(font);
        out.outlinedText=await outlineGeometry(node,true);
      }
    } catch(error) { captureDiagnostics.push({code:'TEXT_OUTLINE_FAILED',message:error.message}); }

  }
  if(Array.isArray(out.strokes)&&out.strokes.some(p=>p.visible!==false)&&typeof node.outlineStroke==='function') {
    try { out.strokeOutline=await outlineGeometry(node,false); }
    catch(error) { captureDiagnostics.push({code:'STROKE_OUTLINE_FAILED',message:error.message}); }

  }
  // Boolean fillGeometry is already resolved; exporting operand children would double-draw.
  if('children' in node && node.type!=='BOOLEAN_OPERATION') {
    const children=Array.from(node.children);
    for(const child of children) if(child.visible!==false) out.children.push(await visit(child,depth+1,options));
  }
  return out;
}
return {captureNode, audit, ownsTemporaryNode(id){return temporaryIDs.has(id);}, reset(){captureCount=0;}};
}

return {createCapture};
})();
const FME=(()=>{
const {compileScene,compileTransition}=FM;

/** The host and command-line replay share this contract. A Community URL alone
 * is provenance, not source data; only captured Figma nodes enter the compiler. */
const CAPTURE_FORMAT='mettle-source';
const copy=value=>JSON.parse(JSON.stringify(value));
const finite=value=>typeof value==='number'&&Number.isFinite(value);

function localRenderBounds(snapshot) {
  const matrix=snapshot.absoluteTransform,bounds=snapshot.absoluteRenderBounds;
  if(!Array.isArray(matrix)||matrix.length!==2||matrix.some(row=>!Array.isArray(row)||row.length!==3||!row.every(finite))||
    matrix[0][0]!==1||matrix[0][1]!==0||matrix[1][0]!==0||matrix[1][1]!==1) return null;
  if(!bounds||!['x','y','width','height'].every(key=>finite(bounds[key]))||bounds.width<=0||bounds.height<=0) return null;
  const local={x:bounds.x-matrix[0][2],y:bounds.y-matrix[1][2],width:bounds.width,height:bounds.height};
  return Object.values(local).every(finite)?local:null;
}

/** Only the provider's PNG header determines the raster size. The artwork stays
 * in the captured vector geometry, and the original PNG is a separate reference. */
function referenceViewport(snapshot,png) {
  const bounds=localRenderBounds(snapshot);
  if(!bounds) throw new Error(`Figma reference bounds require an unrotated, unscaled selected root with visible render bounds (${snapshot.name??snapshot.id}).`);
  const signature=[137,80,78,71,13,10,26,10];
  if(!png||!Number.isInteger(png.length)||png.length<33||
    signature.some((byte,index)=>png[index]!==byte)||
    png[8]!==0||png[9]!==0||png[10]!==0||png[11]!==13||
    png[12]!==73||png[13]!==72||png[14]!==68||png[15]!==82||
    Array.from({length:8},(_,index)=>png[index+16]).some(byte=>!Number.isInteger(byte)||byte<0||byte>255)) {
    throw new Error(`Figma did not return a valid PNG reference for ${snapshot.name??snapshot.id}.`);
  }
  const uint32=offset=>png[offset]*0x1000000+png[offset+1]*0x10000+png[offset+2]*0x100+png[offset+3];
  const width=uint32(16),height=uint32(20);
  if(width<1||height<1||width>16384||height>16384) throw new Error('Figma reference dimensions must be between 1 and 16384 pixels.');
  return {x:bounds.x,y:bounds.y,width,height};
}

function findTransitions(root,destination) {
  const literalID=typeof destination==='string';
  const target=literalID?{id:destination}:destination;
  const matches=[],counterparts=new Map();let count=0;
  const layerName=node=>node.name??node.id;
  function counterpart(path) {
    if(!path) return null;
    const key=JSON.stringify(path);
    if(counterparts.has(key)) return counterparts.get(key);
    let node=target;
    for(const name of path) {
      const candidates=(node?.children??[]).filter(child=>child.visible!==false&&layerName(child)===name);
      if(candidates.length!==1) {node=null;break;}
      node=candidates[0];
    }
    counterparts.set(key,node);return node;
  }
  function visit(node,path=[],scope=null,depth=0) {
    if(++count>5000||depth>64) throw new Error('Transition source node/depth budget exceeded');
    if(node.visible===false) return;
    if(node.type==='INSTANCE'||node.type==='COMPONENT') scope={node,path};
    for(const reaction of node.reactions??[]) {
      for(const action of reaction.actions??(reaction.action?[reaction.action]:[])) {
        let matchesDestination=action.destinationId===target.id;
        if(action.navigation==='CHANGE_TO'&&!literalID) {
          // CHANGE_TO applies to its containing instance. A component ID shared
          // by an unrelated destination instance cannot identify that instance.
          // Match the corresponding scope by its unique layer-name path; the
          // selected roots' names may differ between prototype states.
          const corresponding=scope?counterpart(scope.path):null;
          const componentID=corresponding?.type==='COMPONENT'?corresponding.id:
            corresponding?.type==='INSTANCE'?corresponding.sourceComponent?.id:undefined;
          matchesDestination=typeof componentID==='string'&&action.destinationId===componentID;
        }
        if(matchesDestination&&action.transition?.type==='SMART_ANIMATE') {
          if(action.navigation&&!['NAVIGATE','CHANGE_TO'].includes(action.navigation)) continue;
          const delay=reaction.trigger?.type==='AFTER_TIMEOUT'?reaction.trigger.timeout:0;
          if(!finite(delay)||delay<0) throw new Error(`Invalid source delay on ${node.name??node.id}.`);
          matches.push({nodeID:node.id,trigger:copy(reaction.trigger??{}),
            action:copy(action),duration:action.transition.duration,easing:action.transition.easing,delay});
        }
      }
    }
    const children=(node.children??[]).filter(child=>child.visible!==false),counts=new Map();
    for(const child of children) counts.set(layerName(child),(counts.get(layerName(child))??0)+1);
    for(const child of children) visit(child,path&&counts.get(layerName(child))===1?[...path,layerName(child)]:null,scope,depth+1);
  }
  visit(root);
  return matches;
}

function makeCapture(nodes,{mode='motion',startNodeID='auto',duration=.6,loop='once',origin='center',viewport}={},provenance={}) {
  if(!['motion','static','transition'].includes(mode)) throw new Error('Choose Motion, static artwork, or a two-frame transition.');
  const count=mode==='transition'?2:1;
  if(nodes.length!==count) throw new Error(`Select exactly ${count} frame/component${count===2?'s':''}.`);
  if(!['once','loop','pingPong'].includes(loop)) throw new Error('Invalid playback mode.');
  if(!['center','topLeft'].includes(origin)) throw new Error('Invalid transform origin.');
  let ordered=[...nodes],transition=null;
  const options={loop,origin,includeMotion:mode==='motion'};
  if(viewport!==undefined) options.viewport=copy(viewport);
  const notes=[];
  if(viewport===undefined) for(const node of nodes) {
    const bounds=localRenderBounds(node),epsilon=1e-3;
    if(bounds&&finite(node.width)&&finite(node.height)&&
      (bounds.x < -epsilon||bounds.y < -epsilon||bounds.x+bounds.width > node.width+epsilon||bounds.y+bounds.height > node.height+epsilon)) {
      notes.push({severity:'warning',code:'CONTENT_OUTSIDE_CANVAS',nodeID:node.id,
        message:'Visible content extends beyond the selected canvas and will be clipped. For static artwork or two states, enable “Use Figma reference bounds” to include the overflow and save independent source references.'});
    }
  }
  if(mode==='transition') {
    if(nodes[0].id===nodes[1].id) throw new Error('Choose two different frames.');
    if(startNodeID==='auto') {
      const forward=findTransitions(nodes[0],nodes[1]),reverse=findTransitions(nodes[1],nodes[0]);
      if(Boolean(forward.length)===Boolean(reverse.length)) {
        throw new Error(forward.length
          ? 'Both frames have a Smart Animate connection. Choose the start frame explicitly.'
          : 'No Smart Animate connection joins these selections. Choose the start frame to create an explicit A → B clip.');
      }
      if(reverse.length) ordered.reverse();
    } else {
      if(!nodes.some(node=>node.id===startNodeID)) throw new Error('The start frame is no longer selected. Inspect the selection again.');
      if(ordered[0].id!==startNodeID) ordered.reverse();
    }
    const matches=findTransitions(ordered[0],ordered[1]);
    const timingKeys=new Set(matches.map(match=>JSON.stringify([match.duration,match.easing,match.delay])));
    if(timingKeys.size>1) throw new Error('Several source interactions have different timing. Select a pair with one unambiguous transition.');
    transition=matches[0]??null;
    if(transition) {
      if(!finite(transition.duration)||transition.duration<=0) throw new Error('The source transition has no valid duration.');
      if(!transition.easing) throw new Error('The source transition has no captured easing.');
      options.duration=transition.duration;options.easing=transition.easing;options.delay=transition.delay;
      notes.push({severity:'info',code:'SOURCE_TRANSITION',nodeID:transition.nodeID,
        message:`${ordered[0].name} → ${ordered[1].name}: source ${transition.duration}s Smart Animate transition, ${transition.delay}s delay. This clip does not run a prototype state machine.`});
    } else {
      options.duration=duration;options.delay=0;
      notes.push({severity:'warning',code:'EXPLICIT_TRANSITION_TIMING',nodeID:ordered[0].id,
        message:'This is an explicitly requested A → B clip. Timing comes from the panel; no matching source interaction was found.'});
    }
  }
  return {format:CAPTURE_FORMAT,version:1,mode,nodes:copy(ordered),options,transition,notes,provenance:copy(provenance)};
}

function compileCapture(capture) {
  if(capture?.format!==CAPTURE_FORMAT||capture.version!==1) throw new Error('Expected a Mettle source capture (version 1).');
  if(!['motion','static','transition'].includes(capture.mode)) throw new Error('Unknown source capture mode.');
  const count=capture.mode==='transition'?2:1;
  if(!Array.isArray(capture.nodes)||capture.nodes.length!==count) throw new Error(`Capture requires ${count} source nodes.`);
  const options={...capture.options,includeMotion:capture.mode==='motion'};
  const document=capture.mode==='transition'
    ? compileTransition(capture.nodes[0],capture.nodes[1],options)
    : compileScene(capture.nodes[0],options);
  document.diagnostics.push(...(capture.notes??[]));
  if(capture.mode==='motion'&&!summarize(document).bindings) {
    document.diagnostics.push({severity:'warning',code:'NO_MOTION_TRACKS',nodeID:capture.nodes[0].id,
      message:'No executable motion tracks were captured. This export is static. Prototype interactions require the two-frame mode; static library variants do not imply animation.'});
  }
  document.provenance={...capture.provenance,captureFormat:CAPTURE_FORMAT,captureVersion:1,mode:capture.mode,
    sourceNodeIDs:capture.nodes.map(node=>node.id)};
  return document;
}

function summarize(document) {
  let nodes=0,bindings=0,draws=0;
  function visit(node) {nodes++;bindings+=node.bindings.length;draws+=node.draws.length;node.children.forEach(visit);}
  document.scenes.forEach(scene=>visit(scene.root));
  return {nodes,bindings,draws,duration:document.scenes[0]?.duration??0,
    errors:document.diagnostics.filter(issue=>issue.severity==='error').length,
    warnings:document.diagnostics.filter(issue=>issue.severity==='warning').length};
}

return {makeCapture,compileCapture,summarize,referenceViewport};
})();
/* Figma host UI adapter. FM/FMC/FME are injected by build.mjs. */
figma.showUI(__html__, { width: 480, height: 690, themeColors: true });
let busy=false;
let selectionToRestore=null;
const capture=FMC.createCapture(figma);
const captureNode=capture.captureNode;
function notifySelection(reason='selection') {
  if(busy) return;
  figma.ui.postMessage({type:'selection',reason,nodes:Array.from(figma.currentPage.selection).map(node=>({id:node.id,name:node.name,type:node.type}))});
}
if(typeof figma.on==='function') figma.on('selectionchange',()=>{
  if(busy) {
    const nodes=Array.from(figma.currentPage.selection);
    if(selectionToRestore&&nodes.every(node=>!capture.ownsTemporaryNode(node.id))) {
      selectionToRestore={page:figma.currentPage,nodes};
    }
    return;
  }
  notifySelection();
});
notifySelection();
async function createTestFrames() {
  const a=figma.createFrame();a.name='Metal test — A';a.resize(480,320);a.fills=[{type:'SOLID',color:{r:.05,g:.07,b:.12}}];a.cornerRadius=24;
  const shape=figma.createEllipse();a.appendChild(shape);shape.name='Orb';shape.resize(120,120);shape.x=40;shape.y=100;
  shape.fills=[{type:'GRADIENT_LINEAR',gradientTransform:[[1,0,0],[0,1,0]],gradientStops:[{position:0,color:{r:.2,g:.9,b:.8,a:1}},{position:1,color:{r:.6,g:.35,b:1,a:1}}]}];
  const indicator=figma.createRectangle();a.appendChild(indicator);indicator.name='Indicator';indicator.resize(100,12);indicator.x=40;indicator.y=260;indicator.cornerRadius=6;
  indicator.fills=[{type:'SOLID',color:{r:1,g:.75,b:.35}}];
  const b=a.clone();b.name='Metal test — B';b.x=a.x+540;b.children[0].x=300;b.children[1].x=300;b.children[1].opacity=.35;
  await a.setReactionsAsync([{trigger:{type:'ON_CLICK'},actions:[{type:'NODE',destinationId:b.id,navigation:'NAVIGATE',transition:{type:'SMART_ANIMATE',duration:.8,easing:{type:'EASE_IN_AND_OUT'}},preserveScrollPosition:false}]}]);
  figma.currentPage.selection=[a,b];figma.viewport.scrollAndZoomIntoView([a,b]);
  figma.ui.postMessage({type:'notice',text:'Created A/B test frames. Choose two-frame export. Timing is read from the prototype connection.'});
}
figma.ui.onmessage=async message=>{
  if(busy) return;
  busy=true;
  if(message.type==='export') selectionToRestore={page:figma.currentPage,nodes:Array.from(figma.currentPage.selection)};
  let selectionReason='selection';
  try {
    if(message.type==='selection') {busy=false;notifySelection();return;}
    if(message.type==='reveal-node') {
      const node=await figma.getNodeByIdAsync(message.nodeID);
      if(node&&'visible' in node) {figma.currentPage.selection=[node];figma.viewport.scrollAndZoomIntoView([node]);selectionReason='reveal';}
      return;
    }
    if(message.type==='create-test') {await createTestFrames();return;}
    if(message.type!=='export') return;
    const selection=Array.from(figma.currentPage.selection);
    const expected=message.mode==='transition'?2:1;
    if(selection.length!==expected) throw new Error(`Select exactly ${expected} frame/component${expected===2?'s':''}.`);
    if(selection.some(n=>!('width' in n)||!('height' in n))) throw new Error('Selection must have a width and height.');
    if(message.referenceBounds&&!['static','transition'].includes(message.mode)) throw new Error('Figma reference bounds are available for static artwork or two states. A single PNG cannot establish the bounds of a keyframe animation.');
    capture.reset();
    const snapshots=[];
    for(const node of selection) snapshots.push(await captureNode(node,{includeMotion:message.mode==='motion'}));
    const provenance={source:'Figma Plugin API',fileName:figma.root?.name??'',
      fileKey:('fileKey' in figma?figma.fileKey:null)??null};
    let viewport;
    const referenceFrames=[];
    if(message.referenceBounds) {
      let totalBytes=0;
      const exportSettings={format:'PNG',constraint:{type:'SCALE',value:1},contentsOnly:true,useAbsoluteBounds:false};
      provenance.referenceExports=[];
      for(let index=0;index<selection.length;index++) {
        const node=selection[index],bytes=await node.exportAsync(exportSettings);
        if(!bytes||!Number.isInteger(bytes.length)||(totalBytes+=bytes.length)>32*1024*1024) throw new Error('Figma reference PNGs exceed the 32 MiB transport limit. Select smaller source frames.');
        const local=FME.referenceViewport(snapshots[index],bytes);
        if(viewport&&!['x','y','width','height'].every(key=>viewport[key]===local[key])) {
          throw new Error('The selected Figma references have different local viewports. Use matching source frames before exporting a two-state comparison.');
        }
        viewport??=local;
        const fileName=(node.name.replace(/[^a-z0-9_-]+/gi,'-').slice(0,64)||'scene')+`-${index+1}.figma.png`;
        provenance.referenceExports.push({id:node.id,name:node.name,width:local.width,height:local.height,viewport:local,exportSettings});
        referenceFrames.push({name:node.name,fileName,width:local.width,height:local.height,bytes:Array.from(bytes)});
      }
    }
    const source=FME.makeCapture(snapshots,{mode:message.mode,startNodeID:message.startNodeID??'auto',
      loop:message.loop??'once',origin:message.origin??'center',duration:message.duration,viewport},provenance);
    const document=FME.compileCapture(source);
    const blocked=document.diagnostics.some(d=>d.severity==='error')&&!message.allowPartial;
    const filename=(source.nodes[0].name.replace(/[^a-z0-9_-]+/gi,'-').slice(0,64)||'scene')+'.figmetal.json';
    figma.ui.postMessage({type:'result',document,source,summary:FME.summarize(document),filename,blocked,referenceFrames});
  } catch(error) { figma.ui.postMessage({type:'failure',message:error.message??String(error)}); }
  finally {
    // Outline capture restores its own synchronous temporary selections. Keep
    // genuine selections made during asynchronous reads, including deselecting
    // everything. This fallback only handles a surviving plugin-owned node.
    const current=Array.from(figma.currentPage.selection);
    if(selectionToRestore&&current.some(node=>capture.ownsTemporaryNode(node.id))) {
      const real=current.filter(node=>!node.removed&&!capture.ownsTemporaryNode(node.id));
      figma.currentPage.selection=real.length?real:selectionToRestore.page===figma.currentPage?selectionToRestore.nodes.filter(node=>!node.removed&&!capture.ownsTemporaryNode(node.id)):[];
    }
    selectionToRestore=null;
    busy=false;notifySelection(selectionReason);figma.ui.postMessage({type:'ready'});
  }
};
