#!/usr/bin/env python3
"""Compose presentation assets from genuine GPU output and independent references.

Requires Pillow, ffmpeg, and frames generated by render_readme_media.sh.
No font files or source reference images are fed to the Metal renderer.
"""
from pathlib import Path
import json
import shutil
import subprocess
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
MEDIA = ROOT / 'docs/media'
ART = ROOT / 'artifacts/publish'
BG = '#0b0e14'
FG = '#edf4f6'
MUTED = '#9baab5'
ACCENT = '#80e4ca'

def font(size, bold=False):
    candidates = ([f'/System/Library/Fonts/Supplemental/Arial{" Bold" if bold else ""}.ttf',
                   f'/usr/share/fonts/truetype/dejavu/DejaVuSans{"-Bold" if bold else ""}.ttf'])
    for p in candidates:
        if Path(p).is_file():
            return ImageFont.truetype(p, size)
    raise RuntimeError('Set up Arial or DejaVu Sans locally; fonts are not bundled.')

def draw_text(draw, xy, text, size=22, fill=FG, bold=False):
    draw.text(xy, text, font=font(size,bold), fill=fill)

def flatten(path):
    im=Image.open(path).convert('RGBA')
    bg=Image.new('RGBA',im.size,BG);bg.alpha_composite(im)
    return bg.convert('RGB')

def encode_gif(pattern, output, fps=30):
    subprocess.run(['ffmpeg','-y','-v','error','-framerate',str(fps),'-i',str(pattern),
        '-filter_complex','fps=20,split[a][b];[a]palettegen=stats_mode=diff[p];[b][p]paletteuse=dither=sierra2_4a',
        '-loop','0',str(output)],check=True)

def main():
    MEDIA.mkdir(parents=True,exist_ok=True)
    preview=flatten(MEDIA/'native-frame.png')
    hero=Image.new('RGB',(1600,860),BG);d=ImageDraw.Draw(hero)
    d.rounded_rectangle((72,62,343,103),radius=20,fill='#212323',outline='#4b4536')
    draw_text(d,(90,73),'EXPERIMENTAL  /  v0.2',17,'#f2c77e',True)
    draw_text(d,(68,138),'Mettle',128,FG,True)
    draw_text(d,(76,316),'Design in Figma.',44,FG)
    draw_text(d,(76,375),'Move in Metal.',44,ACCENT)
    draw_text(d,(78,481),'A source-based animation compiler',24,MUTED)
    draw_text(d,(78,518),'and native Swift + Metal renderer.',24,MUTED)
    draw_text(d,(78,585),'No Lottie. No browser. No pixel guessing.',20,FG)
    card=(723,135,1530,705)
    d.rounded_rectangle(card,radius=22,fill='#151b25',outline='#303a47',width=1)
    draw_text(d,(746,156),'NATIVE METAL OUTPUT',16,ACCENT,True)
    draw_text(d,(1120,157),'SYNTHETIC VECTOR FIXTURE',14,MUTED)
    scaled=preview.resize((768,512),Image.Resampling.LANCZOS)
    hero.paste(scaled,(743,189))
    d.line((76,758,1524,758),fill='#303a47',width=1)
    draw_text(d,(78,783),'Figma source   →   Mettle exporter   →   Swift evaluator   →   Metal',21,MUTED)
    draw_text(d,(1295,784),'OPEN SOURCE / MIT',17,ACCENT,True)
    hero.save(MEDIA/'hero.png',optimize=True)

    comparison=Image.new('RGB',(1280,598),BG);d=ImageDraw.Draw(comparison)
    draw_text(d,(28,25),'FIGMA / INDEPENDENT REFERENCE',19,MUTED,True)
    draw_text(d,(652,25),'METTLE / NATIVE METAL',19,ACCENT,True)
    for path,xy in [(ROOT/'fixtures/live/conformance.reference.png',(28,78)),
                    (ROOT/'artifacts/phase2/native.png',(652,78))]:
        im=flatten(path)
        if im.size!=(600,420):raise ValueError(f'Unexpected conformance image size: {im.size}')
        comparison.paste(im,xy)
    draw_text(d,(28,530),'Same source geometry. Independent rendering.',21,FG)
    draw_text(d,(28,562),'Conformance artwork, not a production design. Edge antialiasing differs; not pixel-perfect.',17,MUTED)
    comparison.save(MEDIA/'fidelity.png',optimize=True)

    encode_gif(ART/'demo-frames/%04d.png',MEDIA/'native-demo.gif')
    subprocess.run(['ffmpeg','-y','-v','error','-framerate','30','-i',str(ART/'demo-frames/%04d.png'),
        '-c:v','libx264','-pix_fmt','yuv420p','-crf','19','-movflags','+faststart',str(MEDIA/'native-demo.mp4')],check=True)

    refs=ART/'reference-frames';refs.mkdir(exist_ok=True)
    subprocess.run(['ffmpeg','-y','-v','error','-i',str(ROOT/'fixtures/live/motion.reference.mp4'),
        '-start_number','0',str(refs/'%04d.png')],check=True)
    entries=json.loads((ROOT/'artifacts/phase2/motion-native/manifest.json').read_text())['frames']
    strip=ART/'comparison-frames';strip.mkdir(exist_ok=True)
    for entry in entries:
        frame=Image.new('RGB',(688,252),BG);d=ImageDraw.Draw(frame)
        draw_text(d,(16,12),'FIGMA / REFERENCE',14,MUTED,True)
        draw_text(d,(352,12),'METTLE / METAL',14,ACCENT,True)
        ref=flatten(refs/f"{entry['index']:04d}.png")
        native=flatten(ROOT/'artifacts/phase2/motion-native'/entry['file'])
        if ref.size!=native.size or ref.size!=(320,180):raise ValueError('Motion frame size mismatch')
        frame.paste(ref,(16,44));frame.paste(native,(352,44))
        draw_text(d,(16,231),f"Matched source timeline · {entry['time']:.2f} s",12,MUTED)
        frame.save(strip/f"{entry['index']:04d}.png")
    encode_gif(strip/'%04d.png',MEDIA/'figma-vs-mettle.gif')
    shutil.copy2(ROOT/'artifacts/phase2/comparison.json',MEDIA/'comparison.json')
    print('Generated genuine-render README media. The app screenshot is captured separately, without compositing.')

if __name__=='__main__':main()
